# QueryNest MongoDB查询服务配置文件示例
# 复制此文件为 config.yaml 并根据需要修改配置

# MongoDB实例配置
mongodb:
  instances:
    # 生产环境实例示例
    production:
      name: "生产环境"
      environment: "production"
      connection_string: "mongodb://username:password@prod-server:27017/database?authSource=admin"
      description: "生产环境MongoDB实例"
      status: "active"
      
    # 测试环境实例示例
    staging:
      name: "测试环境"
      environment: "staging"
      connection_string: "mongodb://username:password@staging-server:27017/database?authSource=admin"
      description: "测试环境MongoDB实例"
      status: "active"
      
    # 本地开发实例示例
    local:
      name: "本地开发环境"
      environment: "dev"
      connection_string: "mongodb://localhost:27017/querynest_dev"
      description: "本地开发MongoDB实例"
      status: "active"

# 文件存储配置
storage:
  # 元数据存储路径（相对路径或绝对路径）
  metadata_path: "data/metadata"
  # 语义数据存储路径
  semantic_path: "data/semantics"

# 查询安全限制
security:
  # 单次查询最大返回文档数
  max_result_size: 1000
  # 查询超时时间（秒）
  query_timeout: 30

# MCP服务配置
mcp:
  name: "QueryNest"
  version: "1.0.0"
  description: "MongoDB多实例查询服务"

# 日志配置
logging:
  # 日志级别: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: "INFO"
  # 日志格式: json 或 text
  format: "json"
  # 文件日志配置
  file:
    enabled: true
    path: "logs/querynest.log"
    max_size: "100MB"
    backup_count: 5

# 连接池配置
connection_pool:
  # 健康检查间隔（秒）
  health_check_interval: 30
  # 最大重试次数
  max_retries: 3
  # 重试间隔（秒）
  retry_interval: 5

# 工具配置
tools:
  # 工具执行最大重试次数
  max_retries: 3
  # 重试延迟（秒）
  retry_delay: 1.0
  # 退避因子（每次重试延迟乘以此因子）
  backoff_factor: 2.0

# 环境变量支持
# 所有配置项都可以通过环境变量覆盖，格式为: QUERYNEST_<配置路径>
# 例如:
# QUERYNEST_LOGGING_LEVEL=DEBUG
# QUERYNEST_SECURITY_MAX_RESULT_SIZE=500
# QUERYNEST_MONGODB_INSTANCES_LOCAL_STATUS=inactive