# QueryNest MCP MongoDB查询服务配置文件

# MongoDB实例配置
mongodb:
  instances:
    local_test:
      name: "本地测试环境"
      environment: "test"
      connection_string: "mongodb://localhost:27017/querynest_test"
      database: "querynest_test"
      description: "本地测试MongoDB实例"
      status: "active"
      tags: ["test", "local"]
      
    local_dev:
      name: "本地开发环境"
      environment: "dev"
      connection_string: "mongodb://localhost:27017/querynest_dev"
      database: "querynest_dev"
      description: "本地开发MongoDB实例"
      status: "active"
      tags: ["dev", "local"]

# 元数据库配置
metadata:
  # 元数据数据库名称（每个实例都会创建独立的元数据库）
  database_name: "querynest_metadata"
  # 集合名称配置
  collections:
    instances: "instances"
    databases: "databases"
    collections: "collections"
    fields: "fields"
    query_history: "query_history"
  # 数据保留策略
  retention:
    query_history_days: 30
    scan_history_days: 90

# 安全配置
security:
  # 查询权限控制
  permissions:
    # 允许的查询操作
    allowed_operations:
      - "find"
      - "count"
      - "aggregate"
      - "distinct"
    # 禁止的查询操作
    forbidden_operations:
      - "insert"
      - "update"
      - "delete"
      - "drop"
      - "create"
  
  
  # 查询限制
  limits:
    # 最大返回文档数
    max_documents: 1000
    # 查询超时时间（秒）
    query_timeout: 30

  
  # 数据脱敏配置
  data_masking:
    # 是否启用数据脱敏
    enabled: true
    # 需要脱敏的字段模式
    sensitive_field_patterns:
      - "password"
      - "secret"
      - "token"
      - "key"
      - "phone"
      - "email"
      - "id_card"
      - "credit_card"


# MCP服务配置
mcp:
  # 服务器信息
  server:
    name: "QueryNest"
    version: "1.0.0"
    description: "MongoDB多实例查询服务"
  


# 日志配置
logging:
  # 日志级别
  level: "INFO"
  # 日志格式
  format: "json"  # json 或 text
  # 日志输出
  output:
    # 文件输出
    file:
      enabled: true
      path: "logs/querynest.log"
      level: "DEBUG"
      max_size: "100MB"
      backup_count: 5

# 性能配置
performance:
  # 连接池配置
  connection_pool:
    # 健康检查间隔（秒）
    health_check_interval: 30
    # 连接重试次数
    max_retries: 3
    # 重试间隔（秒）
    retry_interval: 5