[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "querynest"
version = "1.0.0"
description = "QueryNest MCP MongoDB查询服务"
requires-python = ">=3.8"
authors = [{name = "QueryNest Team"}]
license = {text = "MIT"}

dependencies = [
    "mcp>=1.0.0",
    "pymongo>=4.0.0",
    "pydantic>=2.0.0",
    "pydantic-settings>=2.0.0",
    "pyyaml>=6.0",
    "structlog>=23.0.0"
]

[project.scripts]
querynest-mcp = "mcp_server:cli_main"